version: "3.8"

services:
#  mysqldb:
#    container_name: mysqldb
#    platform: linux/x86_64
#    image: mysql:8.0.34
#    restart: unless-stopped
#    env_file: ./.env
#    environment:
#      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#      - MYSQL_DATABASE=$MYSQLDB_DATABASE
#      - MYSQL_USER=$MYSQLDB_USER
#      - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#    ports:
#      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
#    volumes:
#      - db:/var/lib/mysql
#    networks:
#      - test1net
  demoapp:
    container_name: demoapp
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    networks:
      - test1net
  webserver:
    build: ./nginx
    depends_on:
      - demoapp
    ports:
      - "80:80"
networks:
  test1net:
    driver: bridge